### ISSUE TITLE
yearly reminder to fix the update button

### ISSUE THREAD

**Issue by JosephE2** [nacrt/SkyblockClient-REPO#276]
💀

**Comment by JosephE2** [comment]
fix it, remove it or do whatever with it but you haven't touched it since a while ago (when i had cool role) or i will give you bettercit flashbacks

**Comment by iHemoX3** [comment]
your yearly reminder to fucking remember that windows is literally preventing the update function, most likely it's gonna get removed cause u s e l e s s

**Comment by Zetvue** [comment]
😂

**Comment by iHemoX3** [comment]
i dont think you can fix it, stop opening issues about this, it's not even an issue it's just disabled lmao

**Comment by JosephE2** [comment]
>or remove it
